import type { Metadata } from 'next';
import './globals.css';

import { Open_Sans } from 'next/font/google';
import { NavBarComponent } from '@/components/nav-bar';
import { FooterComponent } from '@/components/footer';

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={openSans.className}
        style={{ fontSize: '1.5rem' }}
      >
        <div className='min-h-screen flex flex-col'>
          <NavBarComponent />
          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
